name: Android Kernel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      kernel_repo:
        description: 'Kernel source repository URL'
        required: true
        type: string
        default: 'https://github.com/unasir008/android_kernel_samsung_a12.git'
      kernel_branch:
        description: 'Kernel source branch'
        required: true
        type: string
        default: 'a125f-s6'
      toolchain_repo:
        description: 'Toolchain repository URL (optional)'
        required: false
        type: string
      toolchain_branch:
        description: 'Toolchain branch (optional)'
        required: false
        type: string
      anykernel_repo:
        description: 'AnyKernel repository URL'
        required: false
        type: string
        default: 'https://github.com/unasir008/anykernel.git'
      anykernel_branch:
        description: 'AnyKernel branch'
        required: false
        type: string
        default: 'main'

permissions:
  contents: write
  actions: write

env:
  KERNEL_DIR: ${{ github.workspace }}/kernel
  TOOLCHAIN_DIR: ${{ github.workspace }}/toolchain
  ANYKERNEL_DIR: ${{ github.workspace }}/anykernel
  OUTPUT_DIR: out
  RELEASE_NAME: ProjectX_A125f-s6-v${{ github.run_number }}-kernel
  KERNEL_REPO: https://github.com/unasir008/android_kernel_samsung_a12.git
  KERNEL_BRANCH: a125f-s6
  TOOLCHAIN_REPO: ''
  TOOLCHAIN_BRANCH: main
  ANYKERNEL_REPO: https://github.com/unasir008/anykernel.git
  ANYKERNEL_BRANCH: main

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      # Checkout the workflow repository
      - name: Checkout Workflow Repository
        uses: actions/checkout@v4
        with:
          path: workflow

      # Determine kernel and AnyKernel repos
      - name: Set Repositories
        run: |
          echo "KERNEL_REPO=${{ github.event.inputs.kernel_repo || env.KERNEL_REPO }}" >> $GITHUB_ENV
          echo "KERNEL_BRANCH=${{ github.event.inputs.kernel_branch || env.KERNEL_BRANCH }}" >> $GITHUB_ENV
          echo "TOOLCHAIN_REPO=${{ github.event.inputs.toolchain_repo || env.TOOLCHAIN_REPO }}" >> $GITHUB_ENV
          echo "TOOLCHAIN_BRANCH=${{ github.event.inputs.toolchain_branch || env.TOOLCHAIN_BRANCH }}" >> $GITHUB_ENV
          echo "ANYKERNEL_REPO=${{ github.event.inputs.anykernel_repo || env.ANYKERNEL_REPO }}" >> $GITHUB_ENV
          echo "ANYKERNEL_BRANCH=${{ github.event.inputs.anykernel_branch || env.ANYKERNEL_BRANCH }}" >> $GITHUB_ENV

      # Clone the kernel source
      - name: Clone Kernel Source
        run: |
          git clone --depth 1 --branch ${{ env.KERNEL_BRANCH }} ${{ env.KERNEL_REPO }} ${{ env.KERNEL_DIR }}

      # Clone toolchains (if not in kernel repo)
      - name: Clone Toolchains
        if: env.TOOLCHAIN_REPO != ''
        run: |
          mkdir -p ${{ env.TOOLCHAIN_DIR }}
          git clone --depth 1 --branch ${{ env.TOOLCHAIN_BRANCH }} ${{ env.TOOLCHAIN_REPO }} ${{ env.TOOLCHAIN_DIR }}
          mv ${{ env.TOOLCHAIN_DIR }}/toolchains-gcc-12.3.0 ${{ env.TOOLCHAIN_DIR }}/toolchains-gcc-12.3.0
          mv ${{ env.TOOLCHAIN_DIR }}/clang ${{ env.TOOLCHAIN_DIR }}/clang

      # Clone AnyKernel repository
      - name: Clone AnyKernel Repository
        run: |
          git clone --depth 1 --branch ${{ env.ANYKERNEL_BRANCH }} ${{ env.ANYKERNEL_REPO }} ${{ env.ANYKERNEL_DIR }}

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison flex libssl-dev make gcc zip

      # Run build_kernel.sh from kernel source
      - name: Run Build Script
        run: |
          cd ${{ env.KERNEL_DIR }}
          if [[ ! -f build_kernel.sh ]]; then
            echo "Error: build_kernel.sh not found in kernel source"
            exit 1
          fi
          chmod +x build_kernel.sh
          ./build_kernel.sh

      # Package kernel with AnyKernel3
      - name: Package Kernel with AnyKernel3
        run: |
          cd ${{ env.ANYKERNEL_DIR }}
          if [[ ! -f anykernel.sh ]]; then
            echo "Error: anykernel.sh not found in AnyKernel repository"
            exit 1
          fi
          cp ${{ env.KERNEL_DIR }}/out/arch/arm64/boot/Image .
          zip -r9 ${{ env.RELEASE_NAME }}.zip * -x .git README.md *placeholder
          mv ${{ env.RELEASE_NAME }}.zip ${{ env.KERNEL_DIR }}/
          echo "Kernel packaged as ${{ env.RELEASE_NAME }}.zip"

      # Upload the kernel artifact
      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_NAME }}
          path: ${{ env.KERNEL_DIR }}/${{ env.RELEASE_NAME }}.zip
          if-no-files-found: error
          compression-level: 6

      # Create a GitHub Release and upload asset
      - name: Create Release and Upload Asset
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Kernel Build ${{ github.run_number }}
          body: |
            Automated kernel build for commit ${{ github.sha }}.
            Kernel Source: ${{ env.KERNEL_REPO }} (Branch: ${{ env.KERNEL_BRANCH }})
            Built with GCC 12.3.0 and Clang r416183b1.
            Packaged with AnyKernel3: ${{ env.ANYKERNEL_REPO }} (Branch: ${{ env.ANYKERNEL_BRANCH }})
          draft: false
          prerelease: false
          files: ${{ env.KERNEL_DIR }}/${{ env.RELEASE_NAME }}.zip
