name: Android Kernel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  KERNEL_DIR: ${{ github.workspace }}/kernel
  OUTPUT_DIR: out
  RELEASE_NAME: MyKernel-${{ github.sha }}

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      # Checkout the kernel source code
      - name: Checkout Kernel Repository
        uses: actions/checkout@v4
        with:
          path: kernel

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison flex libssl-dev make gcc zip

      # Run the build script
      - name: Run Build Script
        run: |
          cd $KERNEL_DIR
          chmod +x build_kernel.sh
          ./build_kernel.sh package

      # Upload the kernel artifact
      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_NAME }}
          path: ${{ env.KERNEL_DIR }}/${{ env.RELEASE_NAME }}.zip

      # Create a GitHub Release (optional, for push events)
      - name: Create Release
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Kernel Build ${{ github.run_number }}
          body: |
            Automated kernel build for commit ${{ github.sha }}.
            Built with GCC 12.3.0 and Clang r416183b1.
          draft: false
          prerelease: false

      # Upload kernel to release
      - name: Upload Kernel to Release
        if: github.event_name == 'push'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ env.KERNEL_DIR }}/${{ env.RELEASE_NAME }}.zip
          asset_name: ${{ env.RELEASE_NAME }}.zip
          asset_content_type: application/zip￼Enter
